import { ThemeProvider } from '@/providers/ThemeProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import { ConvexClientProvider } from '@/providers/ConvexClientProvider'
import { Toaster } from 'sonner';

import { Provider } from 'react-redux'
import { setupStore, store } from '@/store/store'
import StoreProvider from '@/providers/StoreProvider'
import { EdgeStoreProvider } from '@/lib/edgestore'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Notion',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (

    <html lang="en" suppressHydrationWarning>
      <body className={cn(`dark:bg-dark`, inter.className)}>
        <StoreProvider>
          <ConvexClientProvider>
            <Toaster />
            <ThemeProvider defaultTheme='system' enableSystem disableTransitionOnChange storageKey='notion-theme' attribute='class'>
              <EdgeStoreProvider>
                {children}
              </EdgeStoreProvider>
            </ThemeProvider>

          </ConvexClientProvider>
        </StoreProvider>
      </body>
    </html>

  )
}
