import { ThemeProvider } from '@/providers/ThemeProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import { ConvexClientProvider } from '@/providers/ConvexClientProvider'
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Notion',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en" suppressHydrationWarning>
      <body className={cn(`dark:bg-dark`, inter.className)}>
        <ConvexClientProvider>
          <Toaster />
          <ThemeProvider defaultTheme='system' enableSystem disableTransitionOnChange storageKey='notion-theme' attribute='class'>
            {children}
          </ThemeProvider>

        </ConvexClientProvider>

      </body>
    </html>

  )
}
